services:
  backend-gateway:
    image: csv-analysis-gateway-server
    build: ./backend-gateway
    environment:
      POSTGRES_URL: db-postgres:5432
      DP_SERVERS: http://backend-data-processor-1:5001 http://backend-data-processor-2:5001
    ports:
      - 5000:5000

  backend-data-processor-1:
    image: csv-analysis-data-processor-server
    build: ./backend-data-processor
    environment:
      POSTGRES_URL: db-postgres:5432
  
  backend-data-processor-2:
    image: csv-analysis-data-processor-server
    build: ./backend-data-processor
    environment:
      POSTGRES_URL: db-postgres:5432
  
  db-postgres:
    image: postgres
    container_name: csv-analysis-postgres-db
    restart: always
    environment:
      POSTGRES_USER: susu
      POSTGRES_PASSWORD: potato
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  # db-postgres-admin:
  #   image: dpage/pgadmin4
  #   container_name: csv-analysis-postgres-admin
  #   restart: always
  #   ports:
  #     - 9001:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: susu@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: potato