services:
  db-postgres:
    image: postgres
    container_name: csv-analysis-postgres-db
    restart: always
    environment:
      POSTGRES_USER: susu
      POSTGRES_PASSWORD: potato
    ports:
      - 9000:5432
  
  db-postgres-admin:
    image: dpage/pgadmin4
    container_name: csv-analysis-postgres-admin
    restart: always
    ports:
      - 9001:80
    environment:
      PGADMIN_DEFAULT_EMAIL: sumaiya.sultana.sinthy@gmail.com
      PGADMIN_DEFAULT_PASSWORD: potato