services:
  # frontend-web:
  #   image: csv-analysis-frontend-web
  #   build: ./frontend-web
  #   ports:
  #     - 3000:5173
  
  backend-gateway:
    image: csv-analysis-gateway-server
    build: ./backend-gateway
    ports:
      - 5000:5000

  backend-data-processor:
    image: csv-analysis-data-processor-server
    build: ./backend-data-processor
    ports:
      - 5001:5001
  
  db-postgres:
    image: postgres
    container_name: csv-analysis-postgres-db
    restart: always
    environment:
      POSTGRES_USER: susu
      POSTGRES_PASSWORD: potato
    ports:
      - 9000:5432
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  # db-postgres-admin:
  #   image: dpage/pgadmin4
  #   container_name: csv-analysis-postgres-admin
  #   restart: always
  #   ports:
  #     - 9001:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: susu@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: potato