CREATE TABLE VALID_SESSION_ID (
    SID UUID DEFAULT gen_random_uuid() PRIMARY KEY 
);

CREATE TABLE CAPACITY_INFO (
    SID UUID,
    FILENAME VARCHAR(500),
    CYCLE_NUMBER NUMERIC,
    CAPACITY NUMERIC,
    PRIMARY KEY(SID, FILENAME, CYCLE_NUMBER),
	FOREIGN KEY (SID) REFERENCES VALID_SESSION_ID(SID) ON DELETE CASCADE
);